### ISSUE TITLE
all tests passing?

### ISSUE THREAD

**Issue by aenbar** [learn-co-curriculum/todo-ruby-basics#13]
this lab had all tests passing already the first time i opened it. wither i'm missing somethinng or the instructions aren't super clear.

Also- it doesn't say anywhere in the instructions that the user should run "ruby_basics.rb" - in fact i don't think it was taught that in order to do that the person would have to write `ruby ruby_basics.rb'

Overall this doesn't seem like a great lab to have at this point in the curriculum- or at all. I do like the idea of a review lab, but seems like by using this we're trying to fit a round peg in a square hole.

**Comment by SophieDeBenedetto** [comment]
It's possible you were operating on an older version of this lab. When you clone down and try it out now, it's not the case that all tests are passing, there is no ruby_bassics.rb file and therefore no need to run one and the instructions in the readme are more clear. I'm closing this issue but feel free to re-open a similar one if you still feel this lab isn't a good fit for this part of the curriculum. :)
